### PR TITLE
Refactor/project structure

### PR DESCRIPTION
**Pull request by pastelApe**
Team,

Spent some time refactoring our project to adopt the flask Blueprint model and app factory design. If we agree I can move forward with finishing up the refactor before rebasing main. Modularizing our code will make adding tests and new features easier. Check out the branch and let me know what you think! 

Here is a brief on why the this app structure is beneficial for the team moving forward:

#### 1. **Modular Design**
The app is organized into distinct modules (`main`, `trip`, `models`), each with its own responsibilities. This modular design promotes separation of concerns, making the codebase easier to manage, understand, and maintain. Each module can be developed, tested, and debugged independently, which enhances productivity and reduces the risk of introducing bugs.

#### 2. **Scalability**
The modular structure allows the application to scale efficiently. New features or modules can be added without affecting existing functionality. This is particularly important as the project grows and new requirements emerge.

#### 3. **Reusability**
By organizing code into reusable components, such as models and blueprints, the app encourages code reuse. This reduces duplication and ensures consistency across the application. For example, the `models` module defines database models that can be reused across different parts of the application.

#### 4. **Maintainability**
The clear separation of different parts of the application makes it easier to maintain. Changes in one module are less likely to impact other modules, reducing the complexity of updates and bug fixes. The use of blueprints in Flask helps in organizing routes and views, making the codebase cleaner and more maintainable.

#### 5. **Collaboration**
The structured organization of the app facilitates collaboration among team members. Each developer can work on different modules simultaneously without interfering with each other's work. This parallel development approach speeds up the development process and improves team efficiency.

#### 6. **Configuration Management**
The use of configuration files like `config.py` and `setup.sh` helps in managing project dependencies and environment-specific settings. This ensures that the development, testing, and production environments are consistent, reducing the likelihood of environment-related issues.

#### 7. **Best Practices**
The app structure follows best practices for Flask applications, such as using blueprints for modularity, defining models in a separate `models.py` file, and initializing extensions in the `__init__.py` file. Adhering to these best practices ensures that the application is built on a solid foundation and is easier to extend and maintain.

Xavier

### CODE REVIEW

**Comment by tbizz46** [comment]
Wow. It looks good. You do great work. 

Thanks,
Terence

**Comment by pastelApe** [comment]
Thanks! Hopefully I can wrap up the rest today and have this ready for a merge. Also, I didn't add my personal token to .env and the GitHub checks past 🤷‍♂️ Never used CI/CD before.

**Review by CMSC495-Team1 — APPROVED** [review]
Great job on the refactor! Switching to Flask Blueprints and the app factory pattern is a smart move—it’ll definitely help keep things organized and manageable as we add new features. The modular design you’ve implemented will make it a lot easier to work on different parts of the app independently, which is going to help a lot as we scale. Nice focus on the focus on reusability, particularly with the models. It’s going to save us time and reduce redundancy, which will be really helpful as we continue to develop. The setup changes you made (especially with the configuration and venv setup) will make onboarding and environment consistency smoother for the whole team. I’m very excited to see how things come together once the refactor is finished—let’s move forward with it!

**Comment by pastelApe** [comment]
Sorry team. I had it ready and then my imports got messed up somehow. Took 5 hrs to fix...

**Pull request merged**
