### PR TITLE
Proposal/htmx

### PR DESCRIPTION
**Pull request by pastelApe**
Hey @GChel31 , 

So this is what I was working on all day today. I couldn't have gone this far without the great work you've done with the app so far. Since we are almost to the finish line I thought it might be best to brute force our UX/UI into a more modern and hopefully simpler stack. 

I used Claude AI to help me speed run this version of our project to incorporate HTMX and a free components library called daisyUI, a plugin for tailwind.css. I was honestly shocked at the first rendition of this when I ran it for the first time. Took 10 hours to get to this point. 

I refactored html into components to make it easier to work on and make changes. Still more the can be broken out.

Please pull this branch and test it out.

git@github.com:pastelApe/Team1_TripPlanner.git

then switch to the proposal/htmx branch.

I changed the setup script to just be `. ./setup.sh`. It will now name and create the env automatically. The HTMX, tailwindcss, and daisyUI plugin are all included using CDN links so no need to install node or anything extra. 

Here is the link to daisyUI: https://daisyui.com

Let me know what you think and if this will be something you're interested in continuing. It shouldn't be too much of a lift to transform the rest of your implementations to work with this new setup. 

We can keep going with what we got too if it too much.

### CODE REVIEW

**Comment by pastelApe** [comment]
AS discussed, due to course schedule we will not be pursuing this proposal.

**Comment by tbizz46** [comment]
I came in late to the meeting but that’s fine.

**Comment by pastelApe** [comment]
If you want to check out the new look, feel free to clone it 👍

**Comment by tbizz46** [comment]
👍🏾

**Pull request closed without merging**
